name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy index.html to App Server
        run: |
          scp -o StrictHostKeyChecking=no \
          -i /home/ubuntu/mykey.pem \
          index.html ubuntu@APP_SERVER_IP:/tmp/

      - name: Deploy to Nginx Directory
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i /home/ubuntu/mykey.pem \
          ubuntu@APP_SERVER_IP << EOF

          sudo cp /tmp/index.html /var/www/html/index.html

          EOF
