name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create PEM File
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Copy index.html to App Server
        run: |
          scp -o StrictHostKeyChecking=no \
          -i key.pem \
          index.html \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/

      - name: Deploy to Nginx
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i key.pem \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF

          sudo cp /tmp/index.html /var/www/html/index.html

          EOF
